### ISSUE TITLE
Image on hub.docker.com has not been updated for a while

### ISSUE THREAD

**Issue by randy3k** [rocker-org/r-devel-san-clang#15]
The [image](https://hub.docker.com/r/rocker/r-devel-ubsan-clang) on hub.docker.com has not been updated for a while. It will be great if someone could update it.

**Comment by eddelbuettel** [comment]
Right. And I feel like I just explained the overall situation of the dailies from [here](https://github.com/wch/r-debug) being possibly more useful.  But now I can't find where I wroe that.  Odd.

I'll see what I can do.

**Comment by eddelbuettel** [comment]
I was probably thinking of this thread in issue #14 here.

**Comment by randy3k** [comment]
You must mean this: https://github.com/rocker-org/r-devel-san-clang/issues/14

I should have also searched the closed issues before opening this.

**Comment by eddelbuettel** [comment]
Jinx, we wrote the same minute.  I have since bit the bullet and set a few Actions to build and push so I can try that here.

**Comment by eddelbuettel** [comment]
Now built and pushed:

![image](https://user-images.githubusercontent.com/673121/140651889-1c7fee8a-e580-4025-8632-891ef84a4077.png)

**Comment by randy3k** [comment]
Thanks. 

By the way, just notice that you also pushed the backup file "docker.yaml~". https://github.com/rocker-org/r-devel-san-clang/tree/master/.github/workflows

**Comment by eddelbuettel** [comment]
Now taken care of.  I usually catch that in `magit` before pushing.   

(Is there such a thing as a global gitignore via `~/.gitconfig` ?)

**Comment by randy3k** [comment]
Yes, kind of.

In `~/.gitconfig`,
```
[core]
    excludesfile = ~/.gitignore
```

**Comment by eddelbuettel** [comment]
Perfect, I was just wondering (when I typed the above) how a `~/.gitignore` outside a repo could work, and that is the obvious hookd.  Awesome.  Will set it up.
