### ISSUE TITLE
Package tcl8.7-dev is not available (Mac M1 issue?)

### ISSUE THREAD

**Issue by ablaette** [rocker-org/r-devel-san-clang#17]
Thanks for your great work! Using rocker-org/r-devel-san-clang to check my package RcppCWB on a macMini with the M1 chip, I receive the following warning when starting the image: "The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested"

So I cloned this repo to build the image locally. But I get an error/abort:  "Package tcl8.7-dev is not available". The same for tk8.7-dev. 

I can build the image flawlessly when I go back to tcl8.6-dev and tk8.6-dev.

Maybe the latest version of tcl/tk is not yet available for the arm64 architecture? As an increasing number of users may have M1 machines, it might make sense to stick with tcl/tk 8.6?

**Comment by eddelbuettel** [comment]
As you already cloned it / made your local modifications so I think it would be best if you continued to adjust there: in your deployment, to your needs.

On amd64 we have no such issues and the idea is to remain close(est) to the actual binary package.
