### ISSUE TITLE
accommodate updates to 'littler'

### ISSUE THREAD

**Issue by kevinushey** [rocker-org/r-devel-san-clang#4]
The Dockerfile contains some code to build `littler`:

```
RUN cd /tmp/littler \
    && CC="clang-3.5 -fsanitize=undefined -fno-sanitize=float-divide-by-zero,vptr,function -fno-sanitize-recover" PATH="/usr/local/lib/R/bin/:$PATH" ./bootstrap \
    && ./configure --prefix=/usr \
    && make \
    && make install \
    && cp -vax examples/*.r /usr/local/bin 
```

It looks like `littler` no longer provides a bootstrap script, though? https://github.com/eddelbuettel/littler (moved to the `deprecated` subfolder)

I encountered this when attempting to build the image locally.

**Comment by eddelbuettel** [comment]
Oh, true dat!  Littler has since become a CRAN package so everything is a tad more standardized now.

Let's fix this.  Do you want to send in a PR?

**Comment by eddelbuettel** [comment]
We fixed this and never closed this.  Doing so now.
